### ISSUE TITLE
Reauth support.

### ISSUE THREAD

**Issue by niemyjski** [DanPatten/ha-snoo#4]
I noticed there was a fork and I couldn't open any issues there. Are you planning on contributing that back to the main library or are they unwilling to take changes / not active?

**Comment by DanPatten** [comment]
I'm guessing they are not active, I ended up not really using the integration for anything and will be selling my SNOO soon so probably won't be updating this much more. I did get everything working via the API except for some auth/token expiration issues.

**Comment by niemyjski** [comment]
I sold my first SNOO and then just got a new one 😅. What was the reauth issue and how often did you hit it?

**Comment by niemyjski** [comment]
I just saw the error:

```
First occurred: April 17, 2024 at 4:58:29 PM (279237 occurrences)
Last logged: 7:24:28 AM

Exception in subscribe loop: HTTP Client Error (403): {'message': 'Token is expired.', 'error': True, 'service': 'Access Manager', 'status': 403}
session.request exception: Cannot connect to host happiestbaby.pubnubapi.com:443 ssl:default [Try again]
Exception in subscribe loop: Cannot connect to host happiestbaby.pubnubapi.com:443 ssl:default [Try again]
````

**Comment by niemyjski** [comment]
I wonder how hard it would be to just flow this error through and trigger reconfiguration?

**Comment by grantland** [comment]
> ... I did get everything working via the API except for some auth/token expiration issues.

Is this the issue you're referencing?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pysnoo2/oauth2_session.py", line 386, in _request
    url, headers, data = self._client.add_token(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 217, in add_token
    raise TokenExpiredError()
oauthlib.oauth2.rfc6749.errors.TokenExpiredError: (token_expired) 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/pysnoo2/pubnub.py", line 194, in _refresh_token
    token = await self._authTokenCallback()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysnoo2/snoo.py", line 55, in pubnub_auth
    async with await self.auth.post(SNOO_PUBNUB_AUTH_URL) as resp:
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysnoo2/auth_session.py", line 65, in post
    response = await super().post(url, data=data, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysnoo2/oauth2_session.py", line 392, in _request
    token = auth.fetch_token()
            ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'fetch_token'
```

AFAICT it seems to be failing on fetching a new token upon token expiration
